version: "3.8"

services:
  portfolio:
    image: nginx:alpine
    container_name: portfolio
    ports:
      - "80:80"
    volumes:
      - .:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
